---
- hosts: Cisco
  gather_facts: true

  tasks:
    - name: debug inventory_hostname
      debug:
        var: inventory_hostname
    - name: output facts
      debug:
        var: hostvars[inventory_hostname]
    - debug:
        var: ansible_facts.net_serialnum
    - name: output a csv
      template:
        src: templates/inventory_csv.yml
        dest: ./{{inventory_hostname}}.csv

- hosts: localhost
  gather_facts: false

  tasks:
    - name: output all the keys in hostvars
      debug:
        var: hostvars.keys() | list

    - name: output a unified CSV
      template:
        src: templates/combined_inventory_csv.yml
        dest: ./combined_inventory.csv
